//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aestheticism_Music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administer
    {
        public int AdministerID { get; set; }
        public string AdministerName { get; set; }
        public string AdministerLoginName { get; set; }
        public string AdministerLoginPwd { get; set; }
        public string AdministerPhone { get; set; }
        public string AdministerEmail { get; set; }
    }
}
