//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aestheticism_Music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicListType
    {
        public int MusicListTypeID { get; set; }
        public Nullable<int> SingerID { get; set; }
        public Nullable<int> MusicListID { get; set; }
        public string SingerType { get; set; }
        public string MusicListType1 { get; set; }
    
        public virtual MusicList MusicList { get; set; }
        public virtual Singer Singer { get; set; }
    }
}
